In [1]:
import cv2
import pandas as pd
import numpy as np
import os

from skimage.feature import local_binary_pattern

import warnings

warnings.filterwarnings('ignore')

In [7]:
# Creating array
images = []
labels = []

#Define dataset
Data_path = "./Dataset/Resized/"

#Define Class labels and corresponding Folder names

class_labels = ['Bacterial', 'Fungal', 'Healthy', 'Hypersensitive']
class_folders = ['Bacterial', 'Fungal', 'Healthy', 'Hypersensitive']

#Appending all images

for i in class_folders:
    for filename in os.listdir(Data_path + i):

        # Read the image file directly in grayscale mode
        img = cv2.imread(Data_path + i + '/' + filename, cv2.IMREAD_GRAYSCALE)
        
        lbp = local_binary_pattern(img, P=8, R=1)
        hist, _ = np.histogram(lbp.ravel(), bins=np.arange(0, 8 + 3), range=(0, 8 + 2))
        
        # Add histogram and label to data list
        images.append(hist)
        labels.append(labels)

#Importing images in numpy arrey
images = np.array(images)
labels = np.array(labels)

KeyboardInterrupt: 

In [8]:
images

[array([166728,  43546,   4253,  15254,  51613,  10090,  14819,  27598,
          4449,   1926], dtype=int64),
 array([170186,  47201,   3889,  14058,  51718,  10899,  14019,  26138,
          3926,   2051], dtype=int64),
 array([165099,  45413,   3798,  13642,  52469,  11564,  13600,  26378,
          3915,   1876], dtype=int64),
 array([161490,  42258,   4372,  16330,  50920,   9803,  15624,  29609,
          4546,   1909], dtype=int64),
 array([178781,  48184,   4133,  14197,  54132,  10790,  14621,  26067,
          3976,   2043], dtype=int64),
 array([177668,  46989,   4056,  14094,  54030,  10586,  14336,  25273,
          4023,   2104], dtype=int64),
 array([178874,  48318,   4096,  14841,  54416,  11144,  14655,  26530,
          4085,   2131], dtype=int64),
 array([171814,  45879,   4494,  16277,  52802,  10506,  15903,  28551,
          4422,   2119], dtype=int64),
 array([167195,  44865,   4682,  16347,  51149,   9910,  15786,  29355,
          4514,   1896], dtype=int64),
 

In [ ]:
# Save data and labels to disk
np.save("LBP_features.npy", images)
